Modules:
  #Enable or Disable Action Control
  ActionControl: true
    #Controlls the usage of beds
    BedListener: true
    #Controlls the usage of buckets on blocks an entities
    BucketListener: true
    #Controlls the items a player can craft
    CraftListener: true
    #Controlls the items a player can drop
    DropListener: true
    #Controlls the items a player can enchant
    EnchantListener: true
    #Controllst the blocks a player can interact with
    InteractListener: true
    #Controlls the items and blocks a player can drop
    PickupListener: true
    #Controlls the items a player can throw
    ThrowListener: true
    #Controlls the items a player can use
    UseListener: true
  #Enable or Disable BuildControl
  BuildControl: true
    #Controlls the blocks a player can break. Sperates between can't break, can break but don't receive items and can break
    BreakListener: true
    #Controlls the blocks a player can place.
    PlaceListener: true
  #Enable or Disable ContainerControl
  ContainerControl:
    #Controlls the items a player can place and take from every container
    ContainerListener: true
  #Enable or Disable DamageControl
  DamageControl: true
    #Controlls the damage that a player can deal to entities
    DamageDealByEntityListener: true
    #Controlls the damaga that a player can take from entities
    DamageTakeByEntityListener: true
    #Controlls every damage, a player can take
    DamageTakeListener: true
  #Enable or Disable EntityBehaviour
  EntityBehaviour: true
    #Controlls the entities a player can interact with
    InteractListener: true
    #Controlls on which entities a player can ride
    RideListener: true
    #Controlls which animals a player can tame
    TameListener: true
    #Controlls which animals can take the player as target
    TargetListener: true
  #Enable or Disable PlayerBehaviour
  PlayerBehaviour: true
    #Controlls if the player can get hungry
    HungerListener: true
    #Controlls if a player is allowed to login on the Server. REQUIRES LUCKPERM
    LoginListener: true
  #Enable or Diable PlayerMovement
  PlayerMovement: true
    #Controlls if a player is allowed to glide
    GlideListener: true
    #Controlls if a player is allowed to sneak
    SneakListener: true
    #Controlls if a player is allowed to sprint
    SprintListener: true
    #Controlls if a player is allowed to swim
    SwimListener: true