name: WorldControl
authors: [RainbowdashLabs, Adwirawien, SirYwell]
version: '0.2-BETA'
api-version: 1.15
description: New edition of the old Modifyworld plugin. Worlds administration and action restriction of players.
main: de.eldoria.eldoworldcontrol.EldoWorldControl
commands:
  eldoworldcontrol:
    description: World control settings
    aliases: [ewc]