name: ${project.name}
authors: [Hadde, Adwirawien, SirYwell]
version: ${project.version}
api-version: 1.13
description: ${project.description}
main: de.eldoria.eldoworldcontrol.core.EldoWorldControl
commands:
  worldcontrol:
    description: World control settings
    aliases: [wc]